name: 🛡️ セキュリティ脆弱性報告
description: セキュリティに関する脆弱性を報告するためのテンプレート
title: "[SECURITY] "
labels: ["security", "vulnerability", "urgent"]
assignees:
  - Michimasa-Hiroya

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **重要**: このテンプレートは軽微なセキュリティ問題専用です。
        重大なセキュリティ脆弱性は、公開Issue追跡ツールではなく、
        kushiro.ai.lab@gmail.com に直接ご連絡ください。

  - type: textarea
    id: vulnerability-description
    attributes:
      label: 脆弱性の説明
      description: 発見されたセキュリティ問題の詳細を記載してください
      placeholder: 脆弱性の内容、影響範囲、リスクレベルを記載
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 再現手順
      description: 脆弱性を再現するための手順
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 深刻度
      description: この脆弱性の深刻度を選択してください
      options:
        - Low (軽微)
        - Medium (中程度)
        - High (高) - プライベート報告推奨
        - Critical (重大) - 必ずプライベート報告
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: 影響を受けるバージョン
      description: 脆弱性の影響を受けるバージョンを記載
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: 緩和策・回避方法
      description: 一時的な回避方法がある場合は記載
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 以下の事項を確認してください
      options:
        - label: この脆弱性は重大ではなく、公開報告が適切であることを確認しました
          required: true
        - label: 悪意のある利用を防ぐため、必要以上の詳細は含めていません
          required: true
        - label: 可能な限り責任ある開示を心がけています
          required: true